// Code generated by security/main.go; DO NOT EDIT.
//
// Meta prefix snapshot for the WhatsApp exception (ip_security_messaging.go):
// the address space Meta registers for its own AS32934, collapsed to the
// fewest covering prefixes, sorted IPv4 then IPv6. A flow to TCP/5222 inside
// it is allowed after the BitTorrent signatures and the application
// standards, as the backstop of the WhatsApp Noise detector.
//
// Regenerate with:  go generate ./...   (or: cd security && go run .)
//
// Every release build refreshes it together with the CFAA tables, so like
// them it is identified by SecurityPolicyHash and is not part of
// SecurityPolicyRulesGeneration (ip_provider_diagnostics.go).
//
// Source: the route and route6 objects for origin AS32934 in RADb, the
// registry Meta documents for its address space (whois.radb.net, query
// "-i origin AS32934"), keeping only the objects Meta maintains itself: source
// RADB with mnt-by MAINT-AS32934, and source RIPE with mnt-by fb-neteng,
// facebook-neteng or meta-mnt. Objects third parties registered with origin
// AS32934 (an ISP-hosted cache) and the RPKI-to-IRR conversions are left out.
//
// Generated input provenance v1:
//   - name=radb server=whois.radb.net:43 query="-i origin AS32934" accepted_v4=433 accepted_v6=648 accepted_sha256=0983a4bb399c07c4622db877263c2426408007f1282c4e852dfb88f8ce359c0b prefixes_v4=23 prefixes_v6=5 disposition=accepted_allow

package connect

import (
	"net/netip"
)

// Masked and collapsed, IPv4 then IPv6; the lookup scans the prefixes in
// place rather than expanding them into addresses.
var metaNetworkPrefixes = [...]netip.Prefix{
	// IPv4
	netip.MustParsePrefix("31.13.24.0/21"),
	netip.MustParsePrefix("31.13.64.0/18"),
	netip.MustParsePrefix("45.64.40.0/22"),
	netip.MustParsePrefix("57.141.0.0/20"),
	netip.MustParsePrefix("57.141.16.0/21"),
	netip.MustParsePrefix("57.141.24.0/23"),
	netip.MustParsePrefix("57.144.0.0/14"),
	netip.MustParsePrefix("66.220.144.0/20"),
	netip.MustParsePrefix("69.63.176.0/20"),
	netip.MustParsePrefix("69.171.224.0/19"),
	netip.MustParsePrefix("74.119.76.0/22"),
	netip.MustParsePrefix("102.132.96.0/20"),
	netip.MustParsePrefix("103.4.96.0/22"),
	netip.MustParsePrefix("129.134.0.0/16"),
	netip.MustParsePrefix("147.75.208.0/20"),
	netip.MustParsePrefix("157.240.0.0/16"),
	netip.MustParsePrefix("163.70.128.0/17"),
	netip.MustParsePrefix("163.77.128.0/17"),
	netip.MustParsePrefix("173.252.64.0/18"),
	netip.MustParsePrefix("179.60.192.0/22"),
	netip.MustParsePrefix("185.60.216.0/22"),
	netip.MustParsePrefix("185.89.216.0/22"),
	netip.MustParsePrefix("204.15.20.0/22"),

	// IPv6
	netip.MustParsePrefix("2401:db00::/32"),
	netip.MustParsePrefix("2620:0:1c00::/40"),
	netip.MustParsePrefix("2a03:2880::/31"),
	netip.MustParsePrefix("2a03:2887:ff2c::/47"),
	netip.MustParsePrefix("2a03:83e0::/32"),
}
