// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: extender.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtenderHeader struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DestinationHost string                 `protobuf:"bytes,1,opt,name=DestinationHost,proto3" json:"DestinationHost,omitempty"`
	DestinationPort uint32                 `protobuf:"varint,2,opt,name=DestinationPort,proto3" json:"DestinationPort,omitempty"`
	Timestamp       uint64                 `protobuf:"varint,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Nonce           []byte                 `protobuf:"bytes,4,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Signature       []byte                 `protobuf:"bytes,5,opt,name=Signature,proto3" json:"Signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExtenderHeader) Reset() {
	*x = ExtenderHeader{}
	mi := &file_extender_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtenderHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtenderHeader) ProtoMessage() {}

func (x *ExtenderHeader) ProtoReflect() protoreflect.Message {
	mi := &file_extender_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtenderHeader.ProtoReflect.Descriptor instead.
func (*ExtenderHeader) Descriptor() ([]byte, []int) {
	return file_extender_proto_rawDescGZIP(), []int{0}
}

func (x *ExtenderHeader) GetDestinationHost() string {
	if x != nil {
		return x.DestinationHost
	}
	return ""
}

func (x *ExtenderHeader) GetDestinationPort() uint32 {
	if x != nil {
		return x.DestinationPort
	}
	return 0
}

func (x *ExtenderHeader) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ExtenderHeader) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *ExtenderHeader) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_extender_proto protoreflect.FileDescriptor

const file_extender_proto_rawDesc = "" +
	"\n" +
	"\x0eextender.proto\x12\tbringyour\"\xb6\x01\n" +
	"\x0eExtenderHeader\x12(\n" +
	"\x0fDestinationHost\x18\x01 \x01(\tR\x0fDestinationHost\x12(\n" +
	"\x0fDestinationPort\x18\x02 \x01(\rR\x0fDestinationPort\x12\x1c\n" +
	"\tTimestamp\x18\x03 \x01(\x04R\tTimestamp\x12\x14\n" +
	"\x05Nonce\x18\x04 \x01(\fR\x05Nonce\x12\x1c\n" +
	"\tSignature\x18\x05 \x01(\fR\tSignatureB'Z%github.com/urnetwork/connect/protocolb\x06proto3"

var (
	file_extender_proto_rawDescOnce sync.Once
	file_extender_proto_rawDescData []byte
)

func file_extender_proto_rawDescGZIP() []byte {
	file_extender_proto_rawDescOnce.Do(func() {
		file_extender_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extender_proto_rawDesc), len(file_extender_proto_rawDesc)))
	})
	return file_extender_proto_rawDescData
}

var file_extender_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_extender_proto_goTypes = []any{
	(*ExtenderHeader)(nil), // 0: bringyour.ExtenderHeader
}
var file_extender_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_extender_proto_init() }
func file_extender_proto_init() {
	if File_extender_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extender_proto_rawDesc), len(file_extender_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extender_proto_goTypes,
		DependencyIndexes: file_extender_proto_depIdxs,
		MessageInfos:      file_extender_proto_msgTypes,
	}.Build()
	File_extender_proto = out.File
	file_extender_proto_goTypes = nil
	file_extender_proto_depIdxs = nil
}
