package fingerprint

// golden.go -- the committed golden fixtures and their provenance, and the
// impl-independent generator for the synthetic golden.
//
// a golden is one named Chrome version's ClientHello handshake message, stored
// as raw bytes under testdata/fingerprints with the version in the filename
// (e.g. chrome-133-clienthello-synthetic.bin). Layer A compares connect's
// emitted hello against it; Layer B (the Docker runner) regenerates it from
// real Chrome and stamps the real version.
//
// the golden shipped here is SYNTHETIC: it is the uTLS v1.8.2 HelloChrome_133
// profile that connect parrots, generated by this package, not a capture of
// real Chrome. it pins "connect still matches the uTLS Chrome_133 reference".
// the owner replaces it with a real-Chrome capture (Layer B) to upgrade the
// gate to "connect still matches real Chrome"; the refresh runbook is in
// README.md.

import (
	"embed"
	"fmt"
	"net"
	"os"
	"path/filepath"

	utls "github.com/refraction-networking/utls"
)

// the committed goldens, embedded so any package (connect's own dialers
// included) can load them without a path relative to this directory.
//
//go:embed testdata/fingerprints/*.bin
var goldenFiles embed.FS

// GoldenRef names a committed golden and its provenance. describe() renders the
// provenance into a drift message so a failure says which Chrome version to
// refresh.
type GoldenRef struct {
	// the embedded path of the golden's raw ClientHello bytes.
	Path string
	// the Chrome version the golden represents.
	ChromeVersion string
	// when the golden was captured or generated (ISO date).
	CaptureDate string
	// how the golden was produced, for the drift message and the reviewer.
	Source string
	// whether the golden is synthetic (uTLS, not real Chrome).
	Synthetic bool
}

func (self GoldenRef) describe() string {
	kind := "real-Chrome golden"
	if self.Synthetic {
		kind = "synthetic golden"
	}
	return fmt.Sprintf("the chrome-%s %s (%s, captured %s)", self.ChromeVersion, kind, self.Source, self.CaptureDate)
}

// GoldenChrome133Synthetic is the committed synthetic golden: the uTLS v1.8.2
// HelloChrome_133 profile connect's net_tls_hello.go parrots. it is what Layer
// A gates against until the owner captures a real-Chrome golden.
var GoldenChrome133Synthetic = GoldenRef{
	Path:          "testdata/fingerprints/chrome-133-clienthello-synthetic.bin",
	ChromeVersion: "133",
	CaptureDate:   "2026-10-07",
	Source:        "synthetic, uTLS v1.8.2 HelloChrome_133 via fingerprint.GenerateChromeHello (NOT real Chrome)",
	Synthetic:     true,
}

// Golden is a loaded golden: its provenance, its raw ClientHello handshake
// message, and that message parsed.
type Golden struct {
	Ref         GoldenRef
	Raw         []byte
	Fingerprint *ClientHelloFingerprint
}

// LoadGolden reads and parses an embedded golden. a golden that does not parse
// is an error, so a corrupt fixture fails loudly rather than passing a diff by
// comparing two empty fingerprints.
func LoadGolden(ref GoldenRef) (*Golden, error) {
	raw, err := goldenFiles.ReadFile(ref.Path)
	if err != nil {
		return nil, fmt.Errorf("read golden %s: %w", ref.Path, err)
	}
	fingerprint, err := ParseClientHello(raw)
	if err != nil {
		return nil, fmt.Errorf("parse golden %s: %w", ref.Path, err)
	}
	return &Golden{Ref: ref, Raw: raw, Fingerprint: fingerprint}, nil
}

// GenerateChromeHello builds the uTLS v1.8.2 HelloChrome_133 ClientHello
// handshake message for serverName, off the network: it is the
// impl-independent reference Chrome hello this harness compares against, the
// same profile connect parrots. the returned bytes are the handshake message
// (type, length and body), i.e. the golden's on-disk form.
//
// it is a first-contact hello: no session cache, so no pre_shared_key, as real
// Chrome sends on a first navigation. the alpn and alps are the profile's own
// (h2, http/1.1, and alps), as a Chrome navigation offers.
func GenerateChromeHello(serverName string) ([]byte, error) {
	// a pipe end as the carrier conn: BuildHandshakeState marshals the hello
	// without doing any i/o on it.
	clientConn, serverConn := net.Pipe()
	defer clientConn.Close()
	defer serverConn.Close()
	config := &utls.Config{ServerName: serverName}
	uconn := utls.UClient(clientConn, config, utls.HelloChrome_133)
	defer uconn.Close()
	if err := uconn.BuildHandshakeState(); err != nil {
		return nil, fmt.Errorf("build chrome hello: %w", err)
	}
	raw := uconn.HandshakeState.Hello.Raw
	if len(raw) == 0 {
		return nil, fmt.Errorf("build chrome hello: empty handshake message")
	}
	// a copy: the uconn owns the backing array and closes over it.
	message := make([]byte, len(raw))
	copy(message, raw)
	return message, nil
}

// WriteGoldenFile writes raw to path, creating the directory. the Layer-B
// capture tool and the synthetic-golden generator write a golden this way; the
// path is on disk (a source tree), not the embed fs.
func WriteGoldenFile(path string, raw []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("make golden dir: %w", err)
	}
	if err := os.WriteFile(path, raw, 0o644); err != nil {
		return fmt.Errorf("write golden %s: %w", path, err)
	}
	return nil
}
